### ISSUE TITLE
May I cooperate with you?

### ISSUE THREAD

**Issue by TingyiChen** [msdx321/android_device_xiaomi_markw#1]
Hello,i am a Chinese in hubei province,may I cooperate with you to develop Android for markw:)Thanks.I have created a organization named markw-dev,hope you can join.:)

**Comment by TingyiChen** [comment]
I am a senior high school student:)

**Comment by msdx321** [comment]
点击链接加入群【红米4高配 CM 内测群】：https://jq.qq.com/?_wv=1027&k=42wvzew

TingyiChen <notifications@github.com>于2016年12月26日周一 下午10:49写道：
