### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by Razziell** [msdx321/android_device_xiaomi_markw#4]
Working radio: https://github.com/Vgdn1942/android_device_lenovo_A6020/commit/943553a039ede24247129ac13dff8dab50f1563b
https://github.com/Vgdn1942/android_device_lenovo_A6020/commit/6777a8c3c5e7c6bda1fdffb680cd0763c53fbd05

**Comment by msdx321** [comment]
Thx dude, I know how to bring up FM, be patient plz.

**Comment by Razziell** [comment]
To remember the SIM card settings you need to roll back to this https://github.com/LineageOS/android_frameworks_opt_telephony/commit/6ac081027f188b0e8d858e33d08fde08ed8905c8
