### ISSUE TITLE
Duplicating the value in Android.mk "app"

### ISSUE THREAD

**Issue by Razziell** [msdx321/android_device_xiaomi_markw#5]
Duplicating the value in Android.mk "app":
IMS_SYMLINKS := $(addprefix $(TARGET_OUT_VENDOR_APPS)/app/ims/lib/arm64/,$(notdir $(IMS_LIBS)))
=>
IMS_SYMLINKS := $(addprefix $(TARGET_OUT_VENDOR_APPS)/ims/lib/arm64/,$(notdir $(IMS_LIBS)))

**Comment by msdx321** [comment]
Thanks for pointing it out
